# install.packages("gdata", repos = "http://cran.us.r-project.org")
# install.packages("frontier", repos="http://R-Forge.R-project.org")
library(frontier)
library(gdata)
data(front41Data)
data <- read.xls("data.xlsx", na.strings=c("NA","#DIV/0!"), sheet="Sheet1")
print(data)
print("------\n-------\n------")
print(front41Data)

 sfaResult <- sfa( log( GDP ) ~ log( COR ) + log( EFF ),
          data = data )
       coef( sfaResult, which = "ols" )
       coef( sfaResult, which = "grid" )
       coef( sfaResult )
